micronaut:
  application:
    name: pix

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/pix
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 12345
    dialect: POSTGRES
    schema-generate: CREATE_DROP

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

itau:
  contas:
    url: 'http://localhost:9091'

bcb:
  pix:
    url: 'http://localhost:8082'